name: bias_dbias
channels:
  - conda-forge
dependencies:
  - ipykernel=6.29.5
  - numpy=1.19.5
  - pandas=1.2.4
  - pip
  - python=3.8
  - spacy=3.2.1
  - tensorflow=2.4.1
  - transformers=4.6.1
  - pip:
    - Dbias==0.1.5
    - tf-keras==2.15.0
